/*
    Compatibility shim for building VPN UI plugins outside the plasma-nm source tree.
    When building in-tree, this header is auto-generated by CMake's GenerateExportHeader.
    For out-of-tree plugins, we link against the installed libplasmanm_editor.so and
    import its symbols.
*/

#ifndef PLASMANM_EDITOR_EXPORT_H
#define PLASMANM_EDITOR_EXPORT_H

#ifdef PLASMANM_EDITOR_STATIC_DEFINE
#  define PLASMANM_EDITOR_EXPORT
#else
#  define PLASMANM_EDITOR_EXPORT __attribute__((visibility("default")))
#endif

#endif
